apiVersion: v1
kind: Namespace
metadata:
  name: yapi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: yapi
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: yapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 512Mi
          env:
          - name: TZ
            value: Asia/Shanghai
          - name: MONGO_INITDB_ROOT_USERNAME
            value: wangsiheng@siluzan.com
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: 'zixia@123'
          ports:
          - name: mongo
            containerPort: 27017
            protocol: TCP 
          volumeMounts:
          - name: mongo-pvc
            mountPath: /mnt/azure/mongodb
      volumes:
        - name: mongo-pvc
          persistentVolumeClaim:
            claimName: yapi
